# Project-wide Gradle settings.

# JVM Arguments
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Gradle Build Optimizations
org.gradle.configuration-cache=true
org.gradle.parallel=true

# Kotlin Code Style
kotlin.code.style=official

# AndroidX & Jetifier
android.useAndroidX=true
android.enableJetifier=false

# Build Performance Improvements
android.nonTransitiveRClass=true